name: empirical-zec
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - pandas
  - scipy
  - tqdm
  - pip
  - pip:
    - -e ../fair2.1-calibrate
